[osd]
vertical-align=center
horizontal-align=left
orientation=vertical
timeout=3
x=-1
y=-1
margin=10

[slider]
invert-dir=false
label1=#ico#
label2=#val#

[text]
label=#ico# #val#

[icons]
backlight=󰛨
volume= 
volume-mute=󰖁
mic=󰍬
mic-mute= 
bat-low=󱊡
bat-full= 
bat-charge=󰂄
bat-discharge=󰁾
bat-idel=󰁹
bat-crit=󰂃
wifi= 
ethernet=󰈀 
bluetooth=
