[osd]
vertical-align=center
horizontal-align=left
orientation=vertical
timeout=3
x=-1
y=-1
margin=10

[slider]
invert-dir=false
label1=#ico#
label2=#val#

[text]
label=#ico# #val#

[icons]
backlight=
volume= 
volume-mute=󰖁
mic=󰍬
mic-mute= 
bat-low=󱊡
bat-full= 
bat-charge=󰂄
bat-discharge=󰁾
bat-idel=󰁹
bat-crit=󰂃
wifi= 
ethernet=󰈀 
bluetooth=

[daemon.exec]
# use #val# to get currect value
# backlight=YOUR_COMMEND_TO_EXECUTE
# audio=YOUR_COMMEND_TO_EXECUTE
# audio-mute=YOUR_COMMEND_TO_EXECUTE
# mic=YOUR_COMMEND_TO_EXECUTE
# mic-mute=YOUR_COMMEND_TO_EXECUTE
# bat-crit=YOUR_COMMEND_TO_EXECUTE
# bat-low=YOUR_COMMEND_TO_EXECUTE
# bat-full=YOUR_COMMEND_TO_EXECUTE
# bat-charge=YOUR_COMMEND_TO_EXECUTE
# bat-discharge=YOUR_COMMEND_TO_EXECUTE
# bat-idel=YOUR_COMMEND_TO_EXECUTE
# wifi=YOUR_COMMEND_TO_EXECUTE
# ethernet=YOUR_COMMEND_TO_EXECUTE
# bluetooth=YOUR_COMMEND_TO_EXECUTE

[daemon.native.exec]
# turn off native ui execution not off is execute native ui
# backlight=off
# audio=off
# audio-mute=off
# mic=off
# mic-mute=off
# bat-crit=off
# bat-low=off
# bat-full=off
# bat-charge=off
# bat-discharge=off
# bat-idel=off
# wifi=off
# ethernet=off
# bluetooth=off
